name: momento
description: Dart client for interacting with Momento
version: 0.0.4
repository: https://github.com/momentohq/client-sdk-dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0
  grpc: ^3.2.4
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  protobuf: ^3.1.0
  string_validator: ^1.0.2
  uuid: ^4.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
