name: basic_subscriber
description: A basic example of how to use Momento Topics to subscribe to a topic to receive messages.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  momento: ^0.1.0

dev_dependencies:
  lints: ^2.1.0
