on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    name: Release Please
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          release-type: dart
          package-name: momento
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
  publish:
    runs-on: ubuntu-latest
    name: Publish to pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC
    needs: [release-please]
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      - uses: actions/checkout@v3
      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Publish Dry Run
        run: dart pub publish --dry-run

      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        name: Publish to pub.dev
